### ISSUE TITLE
Uncaught type error - $safeVersion must be string

### ISSUE THREAD

**Issue by zswanson** [reload/github-security-jira#129]
While debugging #128 I created a temporary jira group 'Developers' and assigned my jira api role to that group. Rerunning the github-security-jira action@1.1.0 now results in a fatal error. (the action is still ignoring the actual group name I'm specifying)

```
Run reload/github-security-jira@v1.1.0
  env:
    GH_SECURITY_TOKEN: ***
    JIRA_TOKEN: ***
    JIRA_HOST: https://JIRA_URL
    JIRA_USER: JIRA_USER
    JIRA_PROJECT: ABC
    JIRA_ISSUE_TYPE: Bug
    JIRA_RESTRICTED_COMMENT_ROLE: JIRA_GROUP

Fatal error: Uncaught TypeError: Typed property GitHubSecurityJira\SecurityAlertIssue::$safeVersion must be string, null used in /opt/ghsec-jira/src/SecurityAlertIssue.php:41
Stack trace:
#0 /opt/ghsec-jira/src/SyncCommand.php(94): GitHubSecurityJira\SecurityAlertIssue->__construct(Array)
#1 /opt/ghsec-jira/vendor/symfony/console/Command/Command.php(255): GitHubSecurityJira\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/ghsec-jira/vendor/symfony/console/Application.php(1011): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/ghsec-jira/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(GitHubSecurityJira\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/ghsec-jira/vendor/symfony/console/Applicat in /opt/ghsec-jira/src/SecurityAlertIssue.php on line 41
```

**Comment by arnested** [comment]
Please check if you're using the latest version. This sounds very much like what we fixed in #85.

**Comment by zswanson** [comment]
We eventually threw in the towel on this since I couldn't get a work around. Thought we were using the latest at the time though. I'm not at the same company anymore so I don't have a way to retest the same conditions.

**Comment by arnested** [comment]
I'm going to close this now based on lack of info. You are welcome to reopen if the issue reappears or new insight is gained.
